package com.danielweisshoff.lexer;

public enum TokenType {
    ADD, SUB, MUL, DIV, EQUALS,
    IDENTIFIER, STRING, NUMBER, FLOAT, EOF,
    O_ROUND_BRACKET, C_ROUND_BRACKET,
    COLON, DOT, COMMA,
    NEWLINE,
    O_SQUARE_BRACKET, C_SQUARE_BRACKET, O_CURLY_BRACKET,
    C_CURLY_BRACKET, O_ANGLE_BRACKET, C_ANGLE_BRACKET, SEMICOLON,
}
