package com.danielweisshoff.parser.nodesystem.node;

public enum NodeType {
    IF_NODE, ERROR_NODE, CALL_NODE, BLOCK_NODE,
    //BOOLEAN
    TRUE_NODE, FALSE_NODE,
    //LOOPS
    DO_WHILE_NODE, FOR_NODE, WHILE_NODE,
    //LOGIC - BITWISE
    BITWISE_AND_NODE, BITWISE_OR_NODE,
    //LOGIC
    BOOLEAN_AND_NODE, BOOLEAN_OR_NODE, EQUAL_NODE, LESS_EQUAL_NODE, LESS_NODE, MORE_EQUAL_NODE, MORE_NODE,
    NOT_EQUAL_NODE,
    //DATA
    DECLARE_NODE, DEFINE_NODE, INIT_NODE, VARIABLE_NODE, POINTER_NODE, ADRESS_NODE, PTR_INIT_NODE, ARRAY_NODE,
    ARRAY_GET_FIELD_NODE, ARRAY_SET_FIELD_NODE,
    //DATA - PRIMITIVES
    BYTE_NODE, SHORT_NODE, INTEGER_NODE, LONG_NODE, FLOAT_NODE, DOUBLE_NODE,
    //ASSIGNING - SHORTCUTS
    PRE_INCREMENT_NODE, PRE_DECREMENT_NODE, POST_INCREMENT_NODE, POST_DECREMENT_NODE,
    //BINARY OPERATIONS
    BINARY_ADD_NODE, BINARY_SUB_NODE, BINARY_MUL_NODE, BINARY_DIV_NODE, BINARY_MOD_NODE, NUMBER_NODE,
    //HELPER
    OUT_NODE,
    //FUNCTION
    FUNCTION_NODE,
}
