package lexer;

public enum TokenType {

    O_ROUND_BRACKET, C_ROUND_BRACKET, COLON, DOT, COMMA, O_BLOCK_BRACKET, C_BLOCK_BRACKET, EXCLAMATION, AND, PIPE,
    EQUAL,
    //arithmetic
    PLUS, MINUS, STAR, SLASH, PERCENT,
    //ESCAPE SEQUENCES
    NEWLINE, TAB, EOF,

    //NUMBER REPRESENTATION
    INTEGER, FLOATING_POINT,
    // LITERALS
    IDENTIFIER, STRING, COMMENT,
    //BOOLEAN
    COMPARISON,

    //---KEYWORDS---
    KW_IF, KW_ELSE, KW_ELIF, KW_FNC, KW_WHILE, KW_FOR, KW_DO, KW_OUT,
    //BOOLEAN
    KW_TRUE, KW_FALSE,
    //PRIMITIVES
    KW_BYTE, KW_SHORT, KW_INT, KW_LONG, KW_FLOAT, KW_DOUBLE,
}